# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0002_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='location',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='clothing_admin.Location'),
            preserve_default=False,
        ),
    ]
