# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0003_cohort_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='end_date',
        ),
    ]
