# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0005_batch_batchitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
