# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0007_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='size',
            field=models.CharField(max_length=3),
        ),
    ]
