# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0008_auto_20180627_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_sold',
            field=models.IntegerField(default=0),
        ),
    ]
