# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0012_batchitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='clothing_admin.Color'),
        ),
    ]
