# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0013_auto_20180628_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
