# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Unclaimed', max_length=55),
        ),
    ]
