# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0002_auto_20180627_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clothing_admin.Cohort'),
        ),
    ]
