# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0003_auto_20180627_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='num_items',
            field=models.IntegerField(default=0),
        ),
    ]
