# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_admin', '0008_auto_20180627_2200'),
        ('clothing_dojo', '0011_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='clothing_admin.Cohort'),
            preserve_default=False,
        ),
    ]
