# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0017_auto_20180628_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
