# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_dojo', '0018_auto_20180628_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='clothing_admin.Color'),
        ),
    ]
